wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
batch_size:
  desc: null
  value: 256
buffer_size:
  desc: null
  value: 100000
ensembles:
  desc: null
  value: 5
env:
  desc: null
  value: Pendulum-v0
episodes:
  desc: null
  value: 100
hidden_size:
  desc: null
  value: 256
kstep:
  desc: null
  value: 1
log_video:
  desc: null
  value: 0
mb_lr:
  desc: null
  value: 0.0003
n_rollouts:
  desc: null
  value: 256
n_updates:
  desc: null
  value: 10
run_name:
  desc: null
  value: MBPO-SAC
save_every:
  desc: null
  value: 100
seed:
  desc: null
  value: 1
